import streamlit as st
import pandas as pd
import json
import os

# page setup
st.set_page_config(page_title="Market Tracker", layout="wide", page_icon="🛡️")

st.title("🛡️ Market Tracker Dashboard")
st.markdown("Monitoramento de ativos e metas em tempo real")
st.divider()

# load the data generated by main.py
if os.path.exists("market_status.json"):
    df = pd.read_json("market_status.json")

    # creating quote cards
    st.subheader("Cotações Atuais")
    cols = st.columns(len(df))

    for i, row in enumerate(df.to_dict('records')):
        with cols[i]:
            # color logic: green if the current price is less than or equal to the target price
            is_good_buy = row['Price'] <= row['Target']
            
            st.metric(
                label=f"Moeda: {row['Currency']}", 
                value=f"R$ {row['Price']:.2f}", 
                delta=f"Dif: R$ {row['Difference']:.2f}",
                delta_color="normal" if is_good_buy else "inverse"
            )
            
            if is_good_buy:
                st.success("🚨 ALERTA: HORA DE COMPRAR")
            else:
                st.warning("✅ Aguardando Meta")

    st.divider()

    # detais table
    st.subheader("Detalhes do Pipeline")
    st.dataframe(df, use_container_width=True)

    # history (reading the CSV you created)
    if os.path.exists("market_price.csv"):
        st.divider()
        st.subheader("Evolução dos Preços (Histórico)")
        
        try:
            hist_df = pd.read_csv("market_price.csv", sep=";")
            chart_data = hist_df.pivot(index='Timestamp', columns='Currency', values='Price')
            
            if len(chart_data) > 1:
                st.line_chart(chart_data)
            else:
                st.info("O gráfico precisa de pelo menos 2 capturas em horários diferentes para desenhar a linha.")
                
        except Exception as e:
            st.error(f"Erro ao processar dados: {e}")
    else:
        st.info("Arquivo de histórico (CSV) ainda não foi criado.")