import streamlit as st
import pandas as pd
import json
import os

# Page setup
st.set_page_config(page_title="Market Tracker", layout="wide", page_icon="🛡️")

st.title("🛡️ Market Tracker Dashboard")
st.markdown("Monitoramento de ativos e metas em tempo real")
st.divider()

# Load the data generated by main.py
if os.path.exists("market_status.json"):
    df = pd.read_json("market_status.json")

    # Creating quote cards
    st.subheader("Cotações Atuais")
    cols = st.columns(len(df))

    for i, row in enumerate(df.to_dict('records')):
        with cols[i]:
            # Color logic: green if the current price is less than or equal to the target price
            is_good_buy = row['Price'] <= row['Target']

            st.metric(
                label=f"Moeda: {row['Currency']}",
                value=f"R$ {row['Price']:.2f}",
                delta=f"Dif: R$ {row['Difference']:.2f}",
                delta_color="normal" if is_good_buy else "inverse"
            )

            if is_good_buy:
                st.success("🚨 ALERTA: HORA DE COMPRAR")
            else:
                st.warning("✅ Aguardando Meta")

    st.divider()

st.header("Calculadora de Importação")
st.markdown("Simule o preço de venda final com base nas cotações capturadas pelo pipeline!")

# Creating columns for the inputs
c1, c2, c3 = st.columns(3)

with c1:
    # User chooses the currency that came from the JSON
    currency_options = df['Currency'].unique()
    selected_currency = st.selectbox("Moeda do Produto", currency_options)

with c2:
    # Input for the product price in foreign currency
    origin_price = st.number_input(f"Preço em {selected_currency}", min_value=0.0, value=100.0, step=10.0)

with c3:
    # Profit margin (using the JSON default or leaving it free)
    margin_input = st.number_input("Margem de Lucro (%)", min_value=0.0, value=20.0, step=20.0)

# Fetching the captured quote for the selected currency
used_quote = df[df['Currency'] == selected_currency]['Price'].values[0]
tax_rate = 0.60 # 60% fixed as in the previous code

# Final calculation
converted_price = origin_price * used_quote
sale_price = converted_price * (1 + tax_rate + (margin_input / 100))

# Displaying the result elegantly
st.subheader(f"Preço sugerido para venda: R$ {sale_price:.2f}")

with st.expander("Ver detalhamento do cálculo"):
    st.write(f"**Custo Convertido:** R$ {converted_price:.2f}")
    st.write(f"**Impostos (60%):** R$ {converted_price * 0.60:.2f}")
    st.write(f"**Lucro Esperado ({margin_input}%):** R$ {converted_price * (margin_input / 100):.2f}")

st.divider()

# History (reading the CSV created by the pipeline)
if os.path.exists("market_price.csv"):
    st.subheader("Tendência Individual por Ativo")

try:
    df_hist = pd.read_csv("market_price.csv", sep=";")

    g1, g2, g3 = st.columns(3)
    currencies = ["USD", "EUR", "BTC"]
    chart_columns = [g1, g2, g3]

    for i, currency in enumerate(currencies):
        with chart_columns[i]:

            with st.container(border=True):
                st.markdown(f"#### {currency}")

                currency_data = df_hist[df_hist['Currency'] == currency].sort_values('Timestamp')

                if len(currency_data) > 1:

                    chart_series = currency_data.set_index('Timestamp')['Price']

                    st.line_chart(chart_series, use_container_width=True)

                    last_price = chart_series.iloc[-1]
                    st.caption(f"Última leitura: R$ {last_price:,.2f}")
                else:
                    st.info("Coletando dados...")

except Exception as e:
    st.error(f"Erro ao processar gráficos: {e}")